package clases;
// Generated 11-11-2015 10:14:15 PM by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String idusuario;
     private String email;
     private String clave;

    public Usuarios() {
    }

    public Usuarios(String idusuario, String email, String clave) {
       this.idusuario = idusuario;
       this.email = email;
       this.clave = clave;
    }
   
    public String getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(String idusuario) {
        this.idusuario = idusuario;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }




}


